apiVersion: v1
kind: Service
metadata:
  name: hailo-exporter
  namespace: monitoring
  labels:
    app: hailo-exporter
spec:
  selector:
    app: hailo-exporter
  ports:
    - name: metrics
      port: 9102
      targetPort: 9102
